m2_i_blog_homepage:
    path:     /
    defaults: { _controller: M2IBlogBundle:Index:index }
m2_i_blog_contactpage:
    path:     /contact
    defaults: { _controller: M2IBlogBundle:Index:contact }
m2_i_blog_aboutpage:
    path:     /about
    defaults: { _controller: M2IBlogBundle:Index:about }